tuples=(32,42,546,3,47)
print(tuples)
print(tuples[2])
sets={34,42,53,74,364,43,347,546}
print(sets)
sets.add(123456)
print(sets)
sets={34,42,53,74,364,43,347,546}
sets.pop()
print(sets)
data={1:'Navya',2:'Rahima',3:'Suma',4:'Suvarna'}
print(data[4])
print(len(data))
print(data.pop(2))
keys=['Navya','Rahima','Mohimeen']
values=['python','c++','c']
data=dict(zip(keys,values))
print(data)
print(data['Navya'])
groups={'navya':'deverasetty','rahima':'shaik\'s','shameer':{'c','python'},'gangu':{'peer':'csp','aslam':'mpmc'}}
print(groups)
print(groups['gangu'])
print(groups['gangu']['peer'])
groups['kavya']='webdev'
print(groups)
a=2
b=a+2
print(b)
print(id(2))
print(id(b))
print(type(a))
a=4
b=float(a)
print(b)
print(type(b))
print(complex(b))
d=2
e=4
f=complex(d,e)
print(f)
print(type(f))